spring.application.name=CodeArena

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/code_arena
spring.datasource.username=postgres
spring.datasource.password=postgre123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=updategit status
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true